name: Build, Push to ECR, and Deploy to ECS (Frontend)

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: contract-analysis-frontend
  ECS_CLUSTER: contract-analysis-cluster
  ECS_SERVICE: contract-analysis-frontend-service
  CONTAINER_NAME: contract-analysis-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # ✅ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # ✅ Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ✅ Build and push image
      - name: Build, Tag, and Push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REPOSITORY .
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # ✅ Deploy to ECS
      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment

      # ✅ Notify via email on success
      - name: Send success notification
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "✅ Deploy Success — ${{ github.repository }}"
          to: ${{ github.event.head_commit.author.email }}
          from: ${{ secrets.SMTP_USER }}
          body: |
            ✅ The frontend was successfully deployed to ECS cluster: ${{ env.ECS_CLUSTER }}
            Service: ${{ env.ECS_SERVICE }}
            Time: ${{ github.event.head_commit.timestamp }}

      # ✅ Notify via email on failure
      - name: Send failure notification
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "❌ Deploy Failed — ${{ github.repository }}"
          to: ${{ github.event.head_commit.author.email }}
          from: ${{ secrets.SMTP_USER }}
          body: |
            ❌ The deployment failed.
            Check the GitHub Actions run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
